import { useGSAP } from '@gsap/react'
import gsap from 'gsap'
import { ArrowRight, Baby, BriefcaseBusiness, CakeSlice, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Gem, Gift, Heart, Leaf, MapPin, Palette, PartyPopper, Search, Sparkles, Star, UsersRound, WandSparkles, Zap, type LucideIcon } from 'lucide-react'
import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { Link, useLocation, useParams, useSearchParams } from 'react-router-dom'
import { useBakeryCartActions, useBakeryCatalog, useBakeryProduct } from '../../../features/bakery/useBakery'
import { bakeryAssets, getBakeryProductAsset } from '../../../shared/utils/bakeryAssets'
import { readBakeryCustomer } from '../../../shared/utils/bakerySession'
import { bakeryCategoryLabels } from '../../../prototype/bakery/bakery.seed'
import type { BakeryCategory, BakeryEvent, BakeryProduct, BakeryStyle } from '../../../domain/bakery/bakery.types'
import { BakeryProductCard, BakerySectionTitle, BakeryStatePanel } from '../components/BakeryUi'
import { bakeryHaptic } from '../../../shared/utils/bakeryFavorites'

gsap.registerPlugin(useGSAP)

const events: Array<{ id: BakeryEvent; label: string; helper: string; icon: LucideIcon; color: string; slug?: string }> = [
  { id: 'BIRTHDAY', label: 'Birthday', helper: 'Make a wish', icon: CakeSlice, color: 'lemon' },
  { id: 'ANNIVERSARY', label: 'Anniversary', helper: 'Another chapter', icon: Heart, color: 'coral' },
  { id: 'WEDDING', label: 'Wedding', helper: 'The big day', icon: Gem, color: 'lavender' },
  { id: 'KIDS', label: 'Kids', helper: 'Colour and play', icon: PartyPopper, color: 'blue' },
  { id: 'BABY_SHOWER', label: 'Baby shower', helper: 'A sweet welcome', icon: Baby, color: 'peach' },
  { id: 'CORPORATE', label: 'Office', helper: 'Team moments', icon: BriefcaseBusiness, color: 'green' },
  { id: 'COUPLES', label: 'For two', helper: 'Date-night cakes', icon: UsersRound, color: 'rose' },
  { id: 'GEN_Z', label: 'Trending', helper: 'Made to post', icon: Zap, color: 'violet', slug: 'gen-z' },
  { id: 'CUSTOM', label: 'Custom', helper: 'Start with an idea', icon: WandSparkles, color: 'cream' },
]

const styles: Array<{ id: BakeryStyle; label: string; description: string; image: string }> = [
  { id: 'VINTAGE', label: 'Vintage piping', description: 'Bold borders, cherries and old-school charm.', image: bakeryAssets.product.vintage },
  { id: 'FLORAL', label: 'Floral garden', description: 'Delicate colour and celebration blooms.', image: bakeryAssets.product.floral },
  { id: 'CHOCOLATE', label: 'Chocolate drama', description: 'Ganache, truffles and deep cocoa.', image: bakeryAssets.product.chocolate },
  { id: 'MINIMAL', label: 'Clean minimal', description: 'Quiet colour, crisp lines and confident details.', image: bakeryAssets.gallery.minimalWhite },
  { id: 'KOREAN', label: 'Korean minimal', description: 'Soft palettes and small, thoughtful statements.', image: bakeryAssets.gallery.celebrationChocolate },
  { id: 'COQUETTE', label: 'Coquette bows', description: 'Romantic bows, ribbons and delicate piping.', image: bakeryAssets.gallery.pastelParty },
  { id: 'RETRO', label: 'Retro cherry', description: 'Throwback piping with playful colour.', image: bakeryAssets.gallery.pinkCelebration },
  { id: 'LUXE', label: 'Pearl luxe', description: 'Refined tiers, pearls and modern wedding detail.', image: bakeryAssets.gallery.celebrationChocolate },
  { id: 'PHOTO', label: 'Photo stories', description: 'Personal memories turned into edible artwork.', image: bakeryAssets.hero },
  { id: 'KIDS', label: 'Playful kids', description: 'Bright, joyful themes for little imaginations.', image: bakeryAssets.gallery.pastelParty },
  { id: 'FUSION', label: 'Indian fusion', description: 'Familiar mithai flavours in a modern cake.', image: bakeryAssets.product.floral },
  { id: 'BENTO', label: 'Tiny bento', description: 'Small cakes with big personality.', image: bakeryAssets.product.vintage },
]

const marqueeItems = ['MADE TO ORDER', 'EGGLESS AVAILABLE', 'CLEAR LEAD TIMES', 'HAND-FINISHED IN CUTTACK']

const heroSlides = [
  { eyebrow: 'CUSTOM CAKE STUDIO', title: 'MAKE THE CAKE THE MOMENT.', copy: 'Choose a beautiful starting point, then make every detail yours.', image: bakeryAssets.hero, alt: 'Colourful handcrafted celebration cake', cta: 'DESIGN YOURS', to: '/bakery/app/design/cake-vintage-heart' },
  { eyebrow: 'TRENDING RIGHT NOW', title: 'MAIN CHARACTER CAKES.', copy: 'Camera-ready bows, bento sets and retro piping for your kind of celebration.', image: bakeryAssets.gallery.pastelParty, alt: 'Pastel celebration cakes', cta: 'SHOP THE DROP', to: '/bakery/app/events/gen-z' },
  { eyebrow: 'CAKES FOR TWO', title: 'ONE SWEET STORY.', copy: 'Date-night bento sets and anniversary cakes made for sharing.', image: bakeryAssets.gallery.pinkCelebration, alt: 'Chocolate celebration cake for a couple', cta: 'EXPLORE FOR TWO', to: '/bakery/app/events/couples' },
  { eyebrow: 'SEND AN IDEA', title: 'FOUND IT ONLINE? MAKE IT YOURS.', copy: 'Share the reference. Our bakers will review the detail, timing and price.', image: bakeryAssets.gallery.minimalWhite, alt: 'Decorated birthday cake inspiration', cta: 'UPLOAD A REFERENCE', to: '/bakery/app/bespoke' },
]

export function BakeryHomePage() {
  const catalog = useBakeryCatalog(); const customer = readBakeryCustomer(); const products = catalog.data?.products ?? []
  const [fulfillment, setFulfillment] = useState<'DELIVERY' | 'PICKUP'>('DELIVERY'); const [fulfillmentOpen, setFulfillmentOpen] = useState(false)
  const [heroIndex, setHeroIndex] = useState(0)
  const best = products.filter((product) => product.bestseller).slice(0, 4); const ready = products.filter((product) => product.readyToday && product.category !== 'CAKES').slice(0, 4)
  const hero = heroSlides[heroIndex]
  useEffect(() => {
    if (matchMedia('(prefers-reduced-motion: reduce)').matches) return
    const timer = window.setInterval(() => setHeroIndex((index) => (index + 1) % heroSlides.length), 5500)
    return () => window.clearInterval(timer)
  }, [])
  const moveHero = (next: number) => { setHeroIndex((next + heroSlides.length) % heroSlides.length); bakeryHaptic() }
  return <div className="bakery-home">
    <section className="bakery-fulfillment"><button type="button" aria-haspopup="dialog" onClick={() => setFulfillmentOpen(true)}><MapPin /><span><small>{fulfillment === 'DELIVERY' ? 'DELIVERY TO' : 'PICKUP FROM'}</small><b>Grand Road, Cuttack</b></span><ChevronRight /></button><Link to="/bakery/app/celebrations"><CalendarDays /><span><small>NEXT CELEBRATION</small><b>Add a date</b></span></Link></section>
    <section className="bakery-app-hero" aria-roledescription="carousel" aria-label="Featured Bakery Wave collections"><div className="bakery-app-hero-art"><img key={hero.image} src={hero.image} alt={hero.alt} fetchPriority="high" /><span>0{heroIndex + 1} / 0{heroSlides.length}</span></div><div className="bakery-app-hero-copy"><span className="bakery-kicker">{hero.eyebrow}</span><h1>{hero.title}</h1><p>{hero.copy}</p><div><Link className="bakery-button primary" to={hero.to}>{hero.cta} <ArrowRight /></Link><Link className="bakery-text-link" to="/bakery/app/cakes">SHOP READY CAKES</Link></div><div className="bakery-hero-controls"><button type="button" onClick={() => moveHero(heroIndex - 1)} aria-label="Previous featured cake"><ChevronLeft /></button><div>{heroSlides.map((slide, index) => <button type="button" key={slide.title} className={index === heroIndex ? 'active' : ''} aria-label={`Show slide ${index + 1}: ${slide.title}`} aria-pressed={index === heroIndex} onClick={() => moveHero(index)} />)}</div><button type="button" onClick={() => moveHero(heroIndex + 1)} aria-label="Next featured cake"><ChevronRight /></button></div></div></section>
    <div className="bakery-trust-marquee" aria-label="Bakery promises"><div>{[...marqueeItems, ...marqueeItems].map((item, index) => <span key={`${item}-${index}`}><i>✦</i>{item}</span>)}</div></div>
    <section className="bakery-home-section"><BakerySectionTitle eyebrow="START WITH THE MOMENT" title="WHAT ARE WE CELEBRATING?" /><div className="bakery-event-grid">{events.map((event) => { const Icon = event.icon; return <Link className={event.color} to={`/bakery/app/events/${event.slug ?? event.id.toLowerCase()}`} key={event.id}><Icon /><span><b>{event.label}</b><small>{event.helper}</small></span><ArrowRight /></Link> })}</div></section>
    <section className="bakery-guided-discovery"><div><span className="bakery-kicker">NOT SURE WHAT YOU WANT?</span><h2>FIND THE CAKE BEFORE YOU KNOW THE CAKE.</h2><p>Start with the occasion, mood, budget and flavour. We’ll narrow the counter to ideas that make sense.</p><Link className="bakery-button primary" to="/bakery/app/discover">FIND MY CAKE <ArrowRight /></Link></div><div className="bakery-discovery-links"><Link to="/bakery/app/cakes?budget=999&collection=birthday"><b>7 birthday cakes</b><span>Under ₹1,000</span><ArrowRight /></Link><Link to="/bakery/app/styles/minimal"><b>Minimal ideas</b><span>Clean and modern</span><ArrowRight /></Link><Link to="/bakery/app/events/kids"><b>Kids cakes</b><span>Bright and playful</span><ArrowRight /></Link><Link to="/bakery/app/events/anniversary"><b>Anniversary</b><span>Made for two</span><ArrowRight /></Link></div></section>
    <section className="bakery-order-paths"><BakerySectionTitle eyebrow="YOUR CAKE · YOUR WAY" title="CHOOSE HOW MUCH YOU WANT TO CREATE" /><div><Link to="/bakery/app/cakes"><b>01</b><span><strong>QUICK ORDER</strong><small>Ready styles, no decision fatigue</small></span><ArrowRight /></Link><Link to="/bakery/app/styles/vintage"><b>02</b><span><strong>PERSONALISE A STYLE</strong><small>Change size, flavour, colour and message</small></span><ArrowRight /></Link><Link to="/bakery/app/design/cake-vintage-heart"><b>03</b><span><strong>DESIGN FROM SCRATCH</strong><small>Open the complete cake studio</small></span><ArrowRight /></Link><Link to="/bakery/app/bespoke"><b>04</b><span><strong>BESPOKE REQUEST</strong><small>Wedding, sculpted and large-event cakes</small></span><ArrowRight /></Link></div></section>
    <section className="bakery-home-section"><BakerySectionTitle eyebrow="BAKER-CURATED" title="FIND YOUR STYLE" action={{ label: 'EXPLORE STYLES', to: '/bakery/app/styles/vintage' }} /><div className="bakery-style-grid">{styles.map((style) => <Link to={`/bakery/app/styles/${style.id.toLowerCase().replaceAll('_', '-')}`} key={style.id}><img src={style.image} alt={`${style.label} cake style`} loading="lazy" /><span><b>{style.label}</b><small>{style.description}</small></span></Link>)}</div></section>
    <section className="bakery-home-section"><BakerySectionTitle eyebrow="CUSTOMER FAVOURITES" title="CAKES PEOPLE COME BACK FOR" action={{ label: 'VIEW ALL', to: '/bakery/app/cakes' }} />{catalog.isError ? <BakeryStatePanel title="THE COUNTER DIDN’T LOAD" description="The demo bakery could not be reached just now." actionLabel="TRY AGAIN" onAction={() => void catalog.refetch()} /> : catalog.isLoading ? <div className="bakery-loading-row">Mixing something lovely…</div> : <div className="bakery-product-grid">{best.map((product) => <BakeryProductCard product={product} key={product.id} />)}</div>}</section>
    <section className="bakery-builder-banner"><div><Sparkles /><span className="bakery-kicker">LIVE CAKE STUDIO</span><h2>STYLE IT. FLAVOUR IT. WRITE ON IT.</h2><p>See the price and preparation promise update as you make it yours.</p><Link className="bakery-button primary" to="/bakery/app/design/cake-floral-lavender">OPEN THE STUDIO</Link></div><img src={bakeryAssets.product.floral} alt="Lavender floral custom cake" loading="lazy" /></section>
    <section className="bakery-same-day"><div><Clock3 /><span><small>NEED A CAKE TODAY?</small><h2>SEE WHAT’S ACTUALLY AVAILABLE.</h2><p>Ready-to-order designs with a real pickup promise from 4:30 PM and delivery slots from 6:00 PM.</p></span></div><Link to="/bakery/app/cakes?ready=true">SHOP READY TODAY <ArrowRight /></Link></section>
    <section className="bakery-home-section"><BakerySectionTitle eyebrow="FRESH FROM THE OVEN" title="A LITTLE JOY, READY TODAY" action={{ label: 'DAILY BAKES', to: '/bakery/app/bakes' }} />{catalog.isError ? <BakeryStatePanel title="TODAY’S BAKES ARE HIDING" description="Try the counter again in a moment." actionLabel="RELOAD BAKES" onAction={() => void catalog.refetch()} /> : <div className="bakery-product-grid">{ready.map((product) => <BakeryProductCard product={product} key={product.id} />)}</div>}</section>
    <section className="bakery-seasonal"><div><span className="bakery-kicker">LIMITED DROP</span><h2>AVAILABLE ONLY THIS WEEKEND.</h2><p>Mango cream, coquette bows and Cuttack-inspired festive flavours. When the batch is gone, it is gone.</p><div className="bakery-drop-tags" aria-label="Seasonal Bakery Wave drops"><span>MANGO SEASON</span><span>VALENTINE’S</span><span>MOTHER’S DAY</span><span>RAJA</span><span>RATH YATRA</span><span>DURGA PUJA</span><span>CHRISTMAS</span></div><Link to="/bakery/app/cakes?collection=weekend">EXPLORE THE DROP <ArrowRight /></Link></div><img src={bakeryAssets.gallery.berryLayer} alt="Limited weekend celebration cake" loading="lazy" /></section>
    <section className="bakery-trust-choice"><span>WHY ORDER DIRECT</span><h2>EXPERIENCE + TRUST, NOT ANOTHER DISCOUNT RACE.</h2><div><p><Check /> Design confirmation</p><p><Clock3 /> Reliable slots</p><p><Palette /> Better customisation</p><p><Heart /> Saved cake history</p><p><Star /> Loyalty that follows you</p><p><CalendarDays /> Occasion reminders</p></div></section>
    {customer ? <section className="bakery-points-card"><div><Star /><span>SWEET POINTS</span><h2>182</h2><p>Gold member · ₹880 to Platinum</p></div><div><strong>ONE MORE ORDER</strong><p>Unlock your next celebration milestone and keep your saved designs close.</p><Link to="/bakery/app/rewards">SEE YOUR REWARDS →</Link></div></section> : <section className="bakery-points-card guest"><div><Gift /><span>SWEET POINTS</span><h2>MAKE EVERY CELEBRATION COUNT.</h2></div><div><strong>JOIN ONLY WHEN YOU’RE READY</strong><p>Browse freely. Sign in at checkout to earn points and save cake designs.</p><Link to="/bakery/app/auth?returnTo=/bakery/app/rewards">SEE HOW REWARDS WORK →</Link></div></section>}
    {fulfillmentOpen && <div className="bakery-sheet-backdrop" role="presentation" onMouseDown={() => setFulfillmentOpen(false)}><section className="bakery-choice-sheet" role="dialog" aria-modal="true" aria-labelledby="bakery-fulfillment-title" onMouseDown={(event) => event.stopPropagation()}><span className="bakery-kicker">HOW SHOULD WE HAND IT OVER?</span><h2 id="bakery-fulfillment-title">DELIVERY OR PICKUP</h2><p>Choose the experience you want. The final promise and fee are rechecked in your box.</p><button type="button" className={fulfillment === 'DELIVERY' ? 'selected' : ''} onClick={() => { setFulfillment('DELIVERY'); setFulfillmentOpen(false) }}><MapPin /><span><b>Delivery</b><small>Carefully brought to your address</small></span>{fulfillment === 'DELIVERY' && <Check />}</button><button type="button" className={fulfillment === 'PICKUP' ? 'selected' : ''} onClick={() => { setFulfillment('PICKUP'); setFulfillmentOpen(false) }}><CalendarDays /><span><b>Pickup</b><small>Collect from Grand Road, Cuttack</small></span>{fulfillment === 'PICKUP' && <Check />}</button><button className="bakery-sheet-close" type="button" onClick={() => setFulfillmentOpen(false)}>KEEP {fulfillment}</button></section></div>}
  </div>
}

const dailyCategories: BakeryCategory[] = ['PASTRIES', 'BROWNIES', 'BREADS', 'SAVOURIES', 'GIFTING']

export function BakeryCatalogPage() {
  const catalog = useBakeryCatalog(); const location = useLocation(); const params = useParams(); const [search] = useSearchParams(); const all = catalog.data?.products ?? []
  const isBakes = location.pathname.endsWith('/bakes'); const style = params.styleSlug?.replaceAll('-', '_').toUpperCase() as BakeryStyle | undefined; const event = params.eventSlug?.replaceAll('-', '_').toUpperCase() as BakeryEvent | undefined
  const requestedBudget = Number(search.get('budget') ?? 0); const requestedReady = search.get('ready') === 'true'; const collection = search.get('collection')
  const [category, setCategory] = useState<string>(isBakes ? 'PASTRIES' : 'ALL'); const [readyOnly, setReadyOnly] = useState(false); const [egglessOnly, setEgglessOnly] = useState(false); const [under500, setUnder500] = useState(false)
  useEffect(() => { setCategory(isBakes ? 'PASTRIES' : 'ALL'); setReadyOnly(requestedReady); setEgglessOnly(false); setUnder500(requestedBudget > 0 && requestedBudget <= 500) }, [isBakes, style, event, requestedReady, requestedBudget, collection])
  const products = all.filter((product) => style ? product.style === style : event ? product.events.includes(event) : isBakes ? dailyCategories.includes(product.category) && (category === 'ALL' || product.category === category) : (product.category === 'CAKES' || product.category === 'BENTO') && (category === 'ALL' || product.category === category)).filter((product) => !readyOnly || product.readyToday).filter((product) => !egglessOnly || product.egglessAvailable).filter((product) => !under500 || product.basePrice < 500).filter((product) => !requestedBudget || product.basePrice <= requestedBudget).filter((product) => collection !== 'birthday' || product.events.includes('BIRTHDAY')).filter((product) => collection !== 'weekend' || product.new || product.style === 'FUSION' || product.style === 'COQUETTE').filter((product) => collection !== 'premium' || product.basePrice >= 999)
  const title = collection === 'weekend' ? 'THE WEEKEND DROP' : collection === 'premium' ? 'PREMIUM CELEBRATION CAKES' : requestedBudget ? `BEAUTIFUL CAKES UNDER ₹${requestedBudget.toLocaleString('en-IN')}` : style ? `${style.replaceAll('_', ' ')} CAKES` : event ? `${event.replaceAll('_', ' ')} CAKES` : isBakes ? 'BAKED FRESH TODAY' : requestedReady ? 'CAKES READY TODAY' : 'CAKES FOR EVERY KIND OF HAPPY'
  const categoryOptions: string[] = isBakes ? ['ALL', ...dailyCategories] : ['ALL', 'CAKES', 'BENTO']
  return <div className="bakery-catalog-page"><header className="bakery-page-intro"><span className="bakery-kicker">{requestedReady ? 'LIVE AVAILABILITY · TODAY' : collection === 'weekend' ? 'SMALL BATCH · LIMITED TIME' : 'HANDMADE IN CUTTACK'}</span><h1>{title}</h1><p>{requestedReady ? 'What you see here can be reserved today. Pickup and delivery promises are confirmed before payment.' : isBakes ? 'Small joys, savoury breaks and something sweet for right now.' : 'Quick-order a baker-curated design or open it up and make it completely yours.'}</p></header>
    {!isBakes && !style && !event && <nav className="bakery-budget-collections" aria-label="Shop cakes by budget"><Link className={requestedBudget === 499 ? 'active' : ''} to="/bakery/app/cakes?budget=499">UNDER ₹499</Link><Link className={requestedBudget === 799 ? 'active' : ''} to="/bakery/app/cakes?budget=799">UNDER ₹799</Link><Link className={requestedBudget === 999 ? 'active' : ''} to="/bakery/app/cakes?budget=999">UNDER ₹999</Link><Link className={requestedBudget === 1499 ? 'active' : ''} to="/bakery/app/cakes?budget=1499">UNDER ₹1,499</Link><Link className={collection === 'premium' ? 'active' : ''} to="/bakery/app/cakes?collection=premium">PREMIUM</Link></nav>}
    {event === 'CORPORATE' && <section className="bakery-office-path"><BriefcaseBusiness /><div><span>MONTHLY OFFICE PLAN</span><h2>EVERY TEAM MOMENT, ONE RELIABLE BAKERY.</h2><p>Employee birthdays, cupcakes, gift boxes and scheduled team celebrations with saved preferences.</p></div><Link to="/bakery/app/bespoke">PLAN OFFICE ORDERS <ArrowRight /></Link></section>}
    {!style && !event && <div className="bakery-category-tabs">{categoryOptions.map((item) => <button className={category === item ? 'active' : ''} type="button" key={item} onClick={() => setCategory(item)}>{item === 'ALL' ? 'All' : bakeryCategoryLabels[item]}</button>)}</div>}
    <div className="bakery-catalog-tools"><div className="bakery-filter-chips" aria-label="Filter the bakery"><button type="button" aria-pressed={readyOnly} className={readyOnly ? 'active' : ''} onClick={() => setReadyOnly((value) => !value)}><Clock3 /> Ready today</button><button type="button" aria-pressed={egglessOnly} className={egglessOnly ? 'active' : ''} onClick={() => setEgglessOnly((value) => !value)}><Leaf /> Eggless</button><button type="button" aria-pressed={under500} className={under500 ? 'active' : ''} onClick={() => setUnder500((value) => !value)}>Under ₹500</button></div><div className="bakery-filter-note"><Clock3 /><span><b>{products.filter((product) => product.readyToday).length} ready today</b><small>Preparation times are shown before checkout</small></span></div></div>
    <div className="bakery-mobile-shop-summary" role="status" aria-live="polite"><span><b>{products.length}</b> {products.length === 1 ? 'bake' : 'bakes'} to explore</span><Link to="/bakery/app/search" aria-label="Search the bakery"><Search /> SEARCH</Link></div>
    {catalog.isError ? <BakeryStatePanel title="WE COULDN’T OPEN THE COUNTER" description="Your filters are safe. Retry the bakery connection." actionLabel="TRY AGAIN" onAction={() => void catalog.refetch()} /> : catalog.isLoading ? <div className="bakery-loading-row">Checking today’s counter…</div> : products.length ? <div className="bakery-product-grid">{products.map((product) => <BakeryProductCard product={product} key={product.id} />)}</div> : <BakeryStatePanel title="NOT ON TODAY’S COUNTER" description="Clear a filter, try another category or ask us about a bespoke bake." actionLabel="VIEW ALL CAKES" link="/bakery/app/cakes" />}
  </div>
}

export function BakeryFinderPage() {
  const catalog = useBakeryCatalog()
  const [occasion, setOccasion] = useState<'ANY' | BakeryEvent>('ANY')
  const [style, setStyle] = useState<'ANY' | BakeryStyle>('ANY')
  const [budget, setBudget] = useState(999)
  const [flavour, setFlavour] = useState('ANY')
  const products = useMemo(() => {
    const flavourTerm = flavour.toLowerCase()
    return (catalog.data?.products ?? [])
      .filter((product) => product.category === 'CAKES' || product.category === 'BENTO')
      .filter((product) => occasion === 'ANY' || product.events.includes(occasion))
      .filter((product) => style === 'ANY' || product.style === style)
      .filter((product) => product.basePrice <= budget)
      .sort((a, b) => {
        if (flavour === 'ANY') return Number(Boolean(b.bestseller)) - Number(Boolean(a.bestseller))
        const score = (product: BakeryProduct) => `${product.name} ${product.description} ${product.style ?? ''}`.toLowerCase().includes(flavourTerm) ? 1 : 0
        return score(b) - score(a)
      })
      .slice(0, 8)
  }, [budget, catalog.data, flavour, occasion, style])
  const lead = products[0]

  return <div className="bakery-finder-page"><header className="bakery-page-intro"><span className="bakery-kicker">A LITTLE HELP, ZERO PRESSURE</span><h1>FIND YOUR CAKE</h1><p>Tell us what matters. The inspiration feed updates without hiding the price or preparation time.</p></header><section className="bakery-finder-panel"><div className="bakery-finder-fields"><label><span>Occasion</span><select value={occasion} onChange={(event) => setOccasion(event.target.value as 'ANY' | BakeryEvent)}><option value="ANY">Any happy moment</option>{events.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label><span>Style</span><select value={style} onChange={(event) => setStyle(event.target.value as 'ANY' | BakeryStyle)}><option value="ANY">Show me everything</option>{styles.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label><span>Budget</span><select value={budget} onChange={(event) => setBudget(Number(event.target.value))}><option value="499">Under ₹499</option><option value="799">Under ₹799</option><option value="999">Under ₹999</option><option value="1499">Under ₹1,499</option><option value="9999">Premium</option></select></label><label><span>Flavour</span><select value={flavour} onChange={(event) => setFlavour(event.target.value)}><option value="ANY">Open to ideas</option><option value="Chocolate">Chocolate</option><option value="Vanilla">Vanilla</option><option value="Rasmalai">Rasmalai</option><option value="Berry">Berry</option></select></label></div><div className="bakery-finder-promise"><Sparkles /><span><b>{products.length} GOOD STARTING POINTS</b><small>Save with the heart or open a design to make it yours.</small></span>{lead && <Link to={`/bakery/app/design/${lead.id}`}>MAKE THIS MINE <ArrowRight /></Link>}</div></section>{catalog.isLoading ? <div className="bakery-loading-row">Curating your inspiration feed…</div> : products.length ? <section className="bakery-finder-results"><BakerySectionTitle eyebrow="YOUR INSPIRATION FEED" title="START HERE. CHANGE ANYTHING." /><div className="bakery-product-grid">{products.map((product) => <BakeryProductCard product={product} key={product.id} />)}</div></section> : <BakeryStatePanel title="LET’S OPEN THE SEARCH" description="Try a larger budget or remove one preference to see more starting points." actionLabel="SEE ALL CAKES" link="/bakery/app/cakes" />}</div>
}

const recentSearchKey = 'bakery-wave:recent-searches'

export function BakerySearchPage() {
  const catalog = useBakeryCatalog(); const [query, setQuery] = useState(''); const [recent, setRecent] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem(recentSearchKey) ?? '[]') as string[] } catch { return [] } })
  const normalized = query.toLowerCase().trim()
  const results = useMemo(() => { if (!normalized) return []; const products = catalog.data?.products ?? []; if (/under\s*(₹|rs\.?\s*)?500/.test(normalized)) return products.filter((product) => product.basePrice < 500); if (normalized.includes('ready today')) return products.filter((product) => product.readyToday); if (normalized.includes('eggless')) return products.filter((product) => product.egglessAvailable); const words = normalized.split(/\s+/).filter(Boolean); return products.filter((product) => words.every((word) => `${product.name} ${product.description} ${product.category} ${product.style ?? ''} ${product.events.join(' ')}`.toLowerCase().includes(word))) }, [catalog.data, normalized])
  const popular = ['chocolate', 'birthday', 'eggless', 'ready today', 'floral', 'under 500']
  const commitSearch = (term = query) => { const clean = term.trim(); if (!clean) return; const next = [clean, ...recent.filter((item) => item.toLowerCase() !== clean.toLowerCase())].slice(0, 4); setRecent(next); localStorage.setItem(recentSearchKey, JSON.stringify(next)) }
  const submit = (event: FormEvent) => { event.preventDefault(); commitSearch() }
  return <div className="bakery-search-page"><header className="bakery-page-intro"><span className="bakery-kicker">FIND YOUR HAPPY</span><h1>SEARCH THE BAKERY</h1></header><form className="bakery-search-box" onSubmit={submit}><Search /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cake, flavour, event or budget" /><button type="submit">SEARCH</button></form>{recent.length > 0 && <div className="bakery-popular-search recent"><b>RECENT SEARCHES</b><div>{recent.map((term) => <button type="button" key={term} onClick={() => setQuery(term)}>{term}</button>)}</div></div>}<div className="bakery-popular-search"><b>POPULAR RIGHT NOW</b><div>{popular.map((term) => <button type="button" key={term} onClick={() => { setQuery(term); commitSearch(term) }}>{term}</button>)}</div></div>{catalog.isError ? <BakeryStatePanel title="SEARCH IS TAKING A BREAK" description="Reconnect to the bakery and try that craving again." actionLabel="TRY AGAIN" onAction={() => void catalog.refetch()} /> : normalized && <section><BakerySectionTitle eyebrow={`${results.length} MATCHES`} title={results.length ? `FOR “${query.toUpperCase()}”` : 'NOTHING MATCHED YET'} />{results.length ? <div className="bakery-product-grid">{results.map((product) => <BakeryProductCard product={product} key={product.id} />)}</div> : <BakeryStatePanel title="TRY A BROADER CRAVING" description="Search chocolate, birthday, eggless, ready today or under 500." actionLabel="BROWSE ALL CAKES" link="/bakery/app/cakes" />}</section>}</div>
}

function presetSelections(product: BakeryProduct, kind: 'classic' | 'eggless' | 'party') {
  return product.modifierGroups.filter((group) => group.required).map((group) => {
    let option = group.options.find((item) => item.recommended) ?? group.options[0]
    if (kind === 'eggless' && group.id === 'sponge') option = group.options.find((item) => item.id === 'eggless') ?? option
    if (kind === 'party' && group.id === 'size') option = group.options.find((item) => item.id === 'one-kg') ?? option
    return { groupId: group.id, optionIds: [option.id] }
  })
}

export function BakeryProductPage() {
  const { productId } = useParams(); const productQuery = useBakeryProduct(productId); const catalog = useBakeryCatalog(); const actions = useBakeryCartActions(); const product = productQuery.data
  const [addedPreset, setAddedPreset] = useState<string | null>(null); const pageRef = useRef<HTMLDivElement>(null); const imageRef = useRef<HTMLDivElement>(null)
  useGSAP(() => {
    if (!product || !pageRef.current || !imageRef.current) return
    const media = gsap.matchMedia()
    media.add('(prefers-reduced-motion: no-preference)', () => gsap.fromTo(imageRef.current, { opacity: 0, scale: .97 }, { opacity: 1, scale: 1, duration: .65, ease: 'power2.out' }))
    return () => media.revert()
  }, { scope: pageRef, dependencies: [product?.id] })
  if (productQuery.isLoading) return <div className="bakery-loading-row">Finishing the details…</div>
  if (productQuery.isError) return <BakeryStatePanel title="THAT CAKE DIDN’T LOAD" description="The design is still here—retry the bakery connection." actionLabel="TRY AGAIN" onAction={() => void productQuery.refetch()} />
  if (!product) return <BakeryStatePanel title="WE COULDN’T FIND THAT BAKE" description="It may have moved off today’s counter." actionLabel="BROWSE CAKES" link="/bakery/app/cakes" />
  const addPreset = (kind: 'classic' | 'eggless' | 'party') => actions.add.mutate({ productId: product.id, selections: presetSelections(product, kind) }, { onSuccess: () => setAddedPreset(kind) })
  const related = (catalog.data?.products ?? []).filter((item) => item.id !== product.id && (item.style === product.style || item.category === product.category)).slice(0, 3)
  return <div ref={pageRef} className="bakery-product-story"><div className="bakery-product-page"><div ref={imageRef} className="bakery-detail-image"><img src={getBakeryProductAsset(product.id)} alt={product.name} /><span className="bakery-sticker tasty">{product.bestseller ? 'MOST LOVED' : 'HANDMADE'}</span>{!product.available && <div className="bakery-image-unavailable"><span>BAKING PAUSED</span><b>Temporarily unavailable</b></div>}</div><div className="bakery-detail-copy"><span className="bakery-kicker">{product.style?.replaceAll('_', ' ') ?? bakeryCategoryLabels[product.category]}</span><h1>{product.name}</h1><p>{product.description}</p><div className="bakery-detail-facts"><span><Clock3 /><b>{product.leadHours ? `Ready in ${product.leadHours} hours` : 'Ready now'}</b></span><span><Gift /><b>{product.servingLabel}</b></span>{product.egglessAvailable && <span><Leaf /><b>Eggless available</b></span>}</div><strong className="bakery-detail-price">FROM ₹{product.basePrice}</strong>
    {!product.available ? <BakeryStatePanel title="THIS DESIGN IS RESTING" description="The baker has paused this cake for now. Browse available cakes without losing your place." actionLabel="SEE AVAILABLE CAKES" link="/bakery/app/cakes" /> : product.customisable ? <><div className="bakery-quick-heading"><span>QUICK ORDER OR MAKE IT YOURS</span><h2>PICK A READY FORMAT</h2><p>Three balanced combinations, ready to add immediately. Personalisation stays available below.</p></div><div className="bakery-preset-grid"><button disabled={actions.add.isPending} onClick={() => addPreset('classic')}><span className="bakery-preset-icon">A</span><b>BAKER’S CLASSIC</b><span>0.5 kg · signature finish</span><strong>{addedPreset === 'classic' ? 'ADDED ✓' : `₹${product.basePrice}`}</strong></button><button disabled={actions.add.isPending} onClick={() => addPreset('eggless')}><span className="bakery-preset-icon">E</span><b>EGGLESS FAVOURITE</b><span>0.5 kg · eggless sponge</span><strong>{addedPreset === 'eggless' ? 'ADDED ✓' : `₹${product.basePrice + 60}`}</strong></button><button disabled={actions.add.isPending} onClick={() => addPreset('party')}><span className="bakery-preset-icon">P</span><b>PARTY SIZE</b><span>1 kg · serves 8–12</span><strong>{addedPreset === 'party' ? 'ADDED ✓' : `₹${product.basePrice + 380}`}</strong></button></div>{actions.add.isError && <p className="bakery-validation">We couldn’t add that format. Please try once more.</p>}<Link className="bakery-button primary wide bakery-sticky-action" to={`/bakery/app/design/${product.id}`}>PERSONALISE THIS CAKE <Sparkles /></Link></> : <button className="bakery-button primary wide" onClick={() => actions.add.mutate({ productId: product.id })}>ADD TO BOX · ₹{product.basePrice}</button>}
    <small className="bakery-detail-note">Final appearance is handcrafted and may vary slightly—that is part of the charm.</small></div></div>
    {product.customisable && <section className="bakery-product-inspiration"><span className="bakery-kicker">START WITH A FEELING</span><h2>ONE CAKE, <span className="bakery-inline-cake"><img src={getBakeryProductAsset(product.id)} alt="" /></span> YOUR MOMENT.</h2><p>Switch the visual direction before opening the studio. Your size, flavour and message remain yours to choose.</p><div className="bakery-style-accordion">{styles.map((style) => <Link key={style.id} to={`/bakery/app/styles/${style.id.toLowerCase()}`} style={{ backgroundImage: `linear-gradient(180deg, transparent 35%, rgba(45, 22, 18, .84)), url(${style.image})` }}><span><Palette />{style.label}</span><p>{style.description}</p></Link>)}</div></section>}
    {related.length > 0 && <section className="bakery-product-related"><BakerySectionTitle eyebrow="KEEP EXPLORING" title="MORE FOR THE MOMENT" /><div className="bakery-product-grid">{related.map((item) => <BakeryProductCard key={item.id} product={item} />)}</div></section>}
    <section className="bakery-product-assurance"><article><Check /><b>PRICE UPDATES LIVE</b><p>No surprise customization cost at checkout.</p></article><article><Clock3 /><b>LEAD TIME SHOWN EARLY</b><p>Choose with the celebration date in mind.</p></article><article><Gift /><b>HAND-FINISHED</b><p>Every design is made by a baker, not a mould.</p></article></section>
  </div>
}
