import { useGSAP } from '@gsap/react'
import gsap from 'gsap'
import { ArrowRight, CalendarDays, Check, ChevronRight, Clock3, Gift, Leaf, MapPin, Palette, Search, Sparkles, Star } from 'lucide-react'
import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { useBakeryCartActions, useBakeryCatalog, useBakeryProduct } from '../../../features/bakery/useBakery'
import { bakeryAssets, getBakeryProductAsset } from '../../../shared/utils/bakeryAssets'
import { readBakeryCustomer } from '../../../shared/utils/bakerySession'
import { bakeryCategoryLabels } from '../../../prototype/bakery/bakery.seed'
import type { BakeryCategory, BakeryEvent, BakeryProduct, BakeryStyle } from '../../../domain/bakery/bakery.types'
import { BakeryProductCard, BakerySectionTitle, BakeryStatePanel } from '../components/BakeryUi'

gsap.registerPlugin(useGSAP)

const events: Array<{ id: BakeryEvent; label: string; emoji: string; color: string }> = [
  { id: 'BIRTHDAY', label: 'Birthday', emoji: '🎂', color: 'lemon' }, { id: 'ANNIVERSARY', label: 'Anniversary', emoji: '💞', color: 'coral' },
  { id: 'WEDDING', label: 'Wedding', emoji: '💍', color: 'lavender' }, { id: 'KIDS', label: 'Kids', emoji: '🎈', color: 'blue' },
  { id: 'BABY_SHOWER', label: 'Baby shower', emoji: '🧸', color: 'peach' }, { id: 'CORPORATE', label: 'Corporate', emoji: '✨', color: 'green' },
]

const styles: Array<{ id: BakeryStyle; label: string; description: string; image: string }> = [
  { id: 'VINTAGE', label: 'Vintage piping', description: 'Bold borders, cherries and old-school charm.', image: bakeryAssets.product.vintage },
  { id: 'FLORAL', label: 'Floral garden', description: 'Delicate colour and celebration blooms.', image: bakeryAssets.product.floral },
  { id: 'CHOCOLATE', label: 'Chocolate drama', description: 'Ganache, truffles and deep cocoa.', image: bakeryAssets.product.chocolate },
]

const marqueeItems = ['MADE TO ORDER', 'EGGLESS AVAILABLE', 'CLEAR LEAD TIMES', 'HAND-FINISHED IN CUTTACK']

export function BakeryHomePage() {
  const catalog = useBakeryCatalog(); const customer = readBakeryCustomer(); const products = catalog.data?.products ?? []
  const [fulfillment, setFulfillment] = useState<'DELIVERY' | 'PICKUP'>('DELIVERY'); const [fulfillmentOpen, setFulfillmentOpen] = useState(false)
  const best = products.filter((product) => product.bestseller).slice(0, 4); const ready = products.filter((product) => product.readyToday && product.category !== 'CAKES').slice(0, 4)
  return <div className="bakery-home">
    <section className="bakery-fulfillment"><button type="button" aria-haspopup="dialog" onClick={() => setFulfillmentOpen(true)}><MapPin /><span><small>{fulfillment === 'DELIVERY' ? 'DELIVERY TO' : 'PICKUP FROM'}</small><b>Grand Road, Cuttack</b></span><ChevronRight /></button><Link to="/bakery/app/celebrations"><CalendarDays /><span><small>NEXT CELEBRATION</small><b>Add a date</b></span></Link></section>
    <section className="bakery-app-hero"><div className="bakery-app-hero-copy"><span className="bakery-kicker">CUSTOM CAKE STUDIO</span><h1>MAKE THE CAKE THE MOMENT.</h1><p>Begin with a style, then shape every delicious detail.</p><div><Link className="bakery-button primary" to="/bakery/app/design/cake-vintage-heart">DESIGN YOURS <ArrowRight /></Link><Link className="bakery-text-link" to="/bakery/app/cakes">SHOP READY CAKES</Link></div></div><div className="bakery-app-hero-art"><img src={bakeryAssets.hero} alt="A colourful handcrafted celebration cake" /><span className="bakery-sticker fresh">BAKED FOR YOU</span></div></section>
    <div className="bakery-trust-marquee" aria-label="Bakery promises"><div>{[...marqueeItems, ...marqueeItems].map((item, index) => <span key={`${item}-${index}`}><i>✦</i>{item}</span>)}</div></div>
    <section className="bakery-home-section"><BakerySectionTitle eyebrow="START WITH THE MOMENT" title="WHAT ARE WE CELEBRATING?" /><div className="bakery-event-grid">{events.map((event) => <Link className={event.color} to={`/bakery/app/events/${event.id.toLowerCase()}`} key={event.id}><span>{event.emoji}</span><b>{event.label}</b></Link>)}</div></section>
    <section className="bakery-order-paths"><BakerySectionTitle eyebrow="YOUR CAKE · YOUR WAY" title="CHOOSE HOW MUCH YOU WANT TO CREATE" /><div><Link to="/bakery/app/cakes"><b>01</b><span><strong>QUICK ORDER</strong><small>Ready styles, no decision fatigue</small></span><ArrowRight /></Link><Link to="/bakery/app/styles/vintage"><b>02</b><span><strong>PERSONALISE A STYLE</strong><small>Change size, flavour, colour and message</small></span><ArrowRight /></Link><Link to="/bakery/app/design/cake-vintage-heart"><b>03</b><span><strong>DESIGN FROM SCRATCH</strong><small>Open the complete cake studio</small></span><ArrowRight /></Link><Link to="/bakery/app/bespoke"><b>04</b><span><strong>BESPOKE REQUEST</strong><small>Wedding, sculpted and large-event cakes</small></span><ArrowRight /></Link></div></section>
    <section className="bakery-home-section"><BakerySectionTitle eyebrow="BAKER-CURATED" title="FIND YOUR STYLE" action={{ label: 'All styles', to: '/bakery/app/styles/vintage' }} /><div className="bakery-style-grid">{styles.map((style) => <Link to={`/bakery/app/styles/${style.id.toLowerCase()}`} key={style.id}><img src={style.image} alt="" loading="lazy" /><span><b>{style.label}</b><small>{style.description}</small></span></Link>)}</div></section>
    <section className="bakery-home-section"><BakerySectionTitle eyebrow="CUSTOMER FAVOURITES" title="CAKES PEOPLE COME BACK FOR" action={{ label: 'See all', to: '/bakery/app/cakes' }} />{catalog.isError ? <BakeryStatePanel title="THE COUNTER DIDN’T LOAD" description="The demo bakery could not be reached just now." actionLabel="TRY AGAIN" onAction={() => void catalog.refetch()} /> : catalog.isLoading ? <div className="bakery-loading-row">Mixing something lovely…</div> : <div className="bakery-product-grid">{best.map((product) => <BakeryProductCard product={product} key={product.id} />)}</div>}</section>
    <section className="bakery-builder-banner"><div><Sparkles /><span className="bakery-kicker">LIVE CAKE STUDIO</span><h2>STYLE IT. FLAVOUR IT. WRITE ON IT.</h2><p>See the price and preparation promise update as you make it yours.</p><Link className="bakery-button primary" to="/bakery/app/design/cake-floral-lavender">OPEN THE STUDIO</Link></div><img src={bakeryAssets.product.floral} alt="Lavender floral custom cake" loading="lazy" /></section>
    <section className="bakery-home-section"><BakerySectionTitle eyebrow="FRESH FROM THE OVEN" title="A LITTLE JOY, READY TODAY" action={{ label: 'Daily bakes', to: '/bakery/app/bakes' }} />{catalog.isError ? <BakeryStatePanel title="TODAY’S BAKES ARE HIDING" description="Try the counter again in a moment." actionLabel="RELOAD BAKES" onAction={() => void catalog.refetch()} /> : <div className="bakery-product-grid">{ready.map((product) => <BakeryProductCard product={product} key={product.id} />)}</div>}</section>
    {customer ? <section className="bakery-points-card"><div><Star /><span>SWEET POINTS</span><h2>182</h2><p>Gold member · ₹880 to Platinum</p></div><div><strong>ONE MORE ORDER</strong><p>Unlock your next celebration milestone and keep your saved designs close.</p><Link to="/bakery/app/rewards">SEE YOUR REWARDS →</Link></div></section> : <section className="bakery-points-card guest"><div><Gift /><span>SWEET POINTS</span><h2>MAKE EVERY CELEBRATION COUNT.</h2></div><div><strong>JOIN ONLY WHEN YOU’RE READY</strong><p>Browse freely. Sign in at checkout to earn points and save cake designs.</p><Link to="/bakery/app/auth?returnTo=/bakery/app/rewards">SEE HOW REWARDS WORK →</Link></div></section>}
    {fulfillmentOpen && <div className="bakery-sheet-backdrop" role="presentation" onMouseDown={() => setFulfillmentOpen(false)}><section className="bakery-choice-sheet" role="dialog" aria-modal="true" aria-labelledby="bakery-fulfillment-title" onMouseDown={(event) => event.stopPropagation()}><span className="bakery-kicker">HOW SHOULD WE HAND IT OVER?</span><h2 id="bakery-fulfillment-title">DELIVERY OR PICKUP</h2><p>Choose the experience you want. The final promise and fee are rechecked in your box.</p><button type="button" className={fulfillment === 'DELIVERY' ? 'selected' : ''} onClick={() => { setFulfillment('DELIVERY'); setFulfillmentOpen(false) }}><MapPin /><span><b>Delivery</b><small>Carefully brought to your address</small></span>{fulfillment === 'DELIVERY' && <Check />}</button><button type="button" className={fulfillment === 'PICKUP' ? 'selected' : ''} onClick={() => { setFulfillment('PICKUP'); setFulfillmentOpen(false) }}><CalendarDays /><span><b>Pickup</b><small>Collect from Grand Road, Cuttack</small></span>{fulfillment === 'PICKUP' && <Check />}</button><button className="bakery-sheet-close" type="button" onClick={() => setFulfillmentOpen(false)}>KEEP {fulfillment}</button></section></div>}
  </div>
}

const dailyCategories: BakeryCategory[] = ['PASTRIES', 'BROWNIES', 'BREADS', 'SAVOURIES', 'GIFTING']

export function BakeryCatalogPage() {
  const catalog = useBakeryCatalog(); const location = useLocation(); const params = useParams(); const all = catalog.data?.products ?? []
  const isBakes = location.pathname.endsWith('/bakes'); const style = params.styleSlug?.toUpperCase() as BakeryStyle | undefined; const event = params.eventSlug?.toUpperCase() as BakeryEvent | undefined
  const [category, setCategory] = useState<string>(isBakes ? 'PASTRIES' : 'ALL'); const [readyOnly, setReadyOnly] = useState(false); const [egglessOnly, setEgglessOnly] = useState(false); const [under500, setUnder500] = useState(false)
  useEffect(() => { setCategory(isBakes ? 'PASTRIES' : 'ALL'); setReadyOnly(false); setEgglessOnly(false); setUnder500(false) }, [isBakes, style, event])
  const products = all.filter((product) => style ? product.style === style : event ? product.events.includes(event) : isBakes ? dailyCategories.includes(product.category) && (category === 'ALL' || product.category === category) : (product.category === 'CAKES' || product.category === 'BENTO') && (category === 'ALL' || product.category === category)).filter((product) => !readyOnly || product.readyToday).filter((product) => !egglessOnly || product.egglessAvailable).filter((product) => !under500 || product.basePrice < 500)
  const title = style ? `${style.replaceAll('_', ' ')} CAKES` : event ? `${event.replaceAll('_', ' ')} CAKES` : isBakes ? 'BAKED FRESH TODAY' : 'CAKES FOR EVERY KIND OF HAPPY'
  const categoryOptions: string[] = isBakes ? ['ALL', ...dailyCategories] : ['ALL', 'CAKES', 'BENTO']
  return <div className="bakery-catalog-page"><header className="bakery-page-intro"><span className="bakery-kicker">HANDMADE IN CUTTACK</span><h1>{title}</h1><p>{isBakes ? 'Small joys, savoury breaks and something sweet for right now.' : 'Quick-order a baker-curated design or open it up and make it completely yours.'}</p></header>
    {!style && !event && <div className="bakery-category-tabs">{categoryOptions.map((item) => <button className={category === item ? 'active' : ''} type="button" key={item} onClick={() => setCategory(item)}>{item === 'ALL' ? 'All' : bakeryCategoryLabels[item]}</button>)}</div>}
    <div className="bakery-catalog-tools"><div className="bakery-filter-chips" aria-label="Filter the bakery"><button type="button" aria-pressed={readyOnly} className={readyOnly ? 'active' : ''} onClick={() => setReadyOnly((value) => !value)}><Clock3 /> Ready today</button><button type="button" aria-pressed={egglessOnly} className={egglessOnly ? 'active' : ''} onClick={() => setEgglessOnly((value) => !value)}><Leaf /> Eggless</button><button type="button" aria-pressed={under500} className={under500 ? 'active' : ''} onClick={() => setUnder500((value) => !value)}>Under ₹500</button></div><div className="bakery-filter-note"><Clock3 /><span><b>{products.filter((product) => product.readyToday).length} ready today</b><small>Preparation times are shown before checkout</small></span></div></div>
    <div className="bakery-mobile-shop-summary" role="status" aria-live="polite"><span><b>{products.length}</b> {products.length === 1 ? 'bake' : 'bakes'} to explore</span><Link to="/bakery/app/search" aria-label="Search the bakery"><Search /> SEARCH</Link></div>
    {catalog.isError ? <BakeryStatePanel title="WE COULDN’T OPEN THE COUNTER" description="Your filters are safe. Retry the bakery connection." actionLabel="TRY AGAIN" onAction={() => void catalog.refetch()} /> : catalog.isLoading ? <div className="bakery-loading-row">Checking today’s counter…</div> : products.length ? <div className="bakery-product-grid">{products.map((product) => <BakeryProductCard product={product} key={product.id} />)}</div> : <BakeryStatePanel title="NOT ON TODAY’S COUNTER" description="Clear a filter, try another category or ask us about a bespoke bake." actionLabel="VIEW ALL CAKES" link="/bakery/app/cakes" />}
  </div>
}

const recentSearchKey = 'bakery-wave:recent-searches'

export function BakerySearchPage() {
  const catalog = useBakeryCatalog(); const [query, setQuery] = useState(''); const [recent, setRecent] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem(recentSearchKey) ?? '[]') as string[] } catch { return [] } })
  const normalized = query.toLowerCase().trim()
  const results = useMemo(() => { if (!normalized) return []; const products = catalog.data?.products ?? []; if (/under\s*(₹|rs\.?\s*)?500/.test(normalized)) return products.filter((product) => product.basePrice < 500); if (normalized.includes('ready today')) return products.filter((product) => product.readyToday); if (normalized.includes('eggless')) return products.filter((product) => product.egglessAvailable); const words = normalized.split(/\s+/).filter(Boolean); return products.filter((product) => words.every((word) => `${product.name} ${product.description} ${product.category} ${product.style ?? ''} ${product.events.join(' ')}`.toLowerCase().includes(word))) }, [catalog.data, normalized])
  const popular = ['chocolate', 'birthday', 'eggless', 'ready today', 'floral', 'under 500']
  const commitSearch = (term = query) => { const clean = term.trim(); if (!clean) return; const next = [clean, ...recent.filter((item) => item.toLowerCase() !== clean.toLowerCase())].slice(0, 4); setRecent(next); localStorage.setItem(recentSearchKey, JSON.stringify(next)) }
  const submit = (event: FormEvent) => { event.preventDefault(); commitSearch() }
  return <div className="bakery-search-page"><header className="bakery-page-intro"><span className="bakery-kicker">FIND YOUR HAPPY</span><h1>SEARCH THE BAKERY</h1></header><form className="bakery-search-box" onSubmit={submit}><Search /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cake, flavour, event or budget" /><button type="submit">SEARCH</button></form>{recent.length > 0 && <div className="bakery-popular-search recent"><b>RECENT SEARCHES</b><div>{recent.map((term) => <button type="button" key={term} onClick={() => setQuery(term)}>{term}</button>)}</div></div>}<div className="bakery-popular-search"><b>POPULAR RIGHT NOW</b><div>{popular.map((term) => <button type="button" key={term} onClick={() => { setQuery(term); commitSearch(term) }}>{term}</button>)}</div></div>{catalog.isError ? <BakeryStatePanel title="SEARCH IS TAKING A BREAK" description="Reconnect to the bakery and try that craving again." actionLabel="TRY AGAIN" onAction={() => void catalog.refetch()} /> : normalized && <section><BakerySectionTitle eyebrow={`${results.length} MATCHES`} title={results.length ? `FOR “${query.toUpperCase()}”` : 'NOTHING MATCHED YET'} />{results.length ? <div className="bakery-product-grid">{results.map((product) => <BakeryProductCard product={product} key={product.id} />)}</div> : <BakeryStatePanel title="TRY A BROADER CRAVING" description="Search chocolate, birthday, eggless, ready today or under 500." actionLabel="BROWSE ALL CAKES" link="/bakery/app/cakes" />}</section>}</div>
}

function presetSelections(product: BakeryProduct, kind: 'classic' | 'eggless' | 'party') {
  return product.modifierGroups.filter((group) => group.required).map((group) => {
    let option = group.options.find((item) => item.recommended) ?? group.options[0]
    if (kind === 'eggless' && group.id === 'sponge') option = group.options.find((item) => item.id === 'eggless') ?? option
    if (kind === 'party' && group.id === 'size') option = group.options.find((item) => item.id === 'one-kg') ?? option
    return { groupId: group.id, optionIds: [option.id] }
  })
}

export function BakeryProductPage() {
  const { productId } = useParams(); const productQuery = useBakeryProduct(productId); const catalog = useBakeryCatalog(); const actions = useBakeryCartActions(); const product = productQuery.data
  const [addedPreset, setAddedPreset] = useState<string | null>(null); const pageRef = useRef<HTMLDivElement>(null); const imageRef = useRef<HTMLDivElement>(null)
  useGSAP(() => {
    if (!product || !pageRef.current || !imageRef.current) return
    const media = gsap.matchMedia()
    media.add('(prefers-reduced-motion: no-preference)', () => gsap.fromTo(imageRef.current, { opacity: 0, scale: .97 }, { opacity: 1, scale: 1, duration: .65, ease: 'power2.out' }))
    return () => media.revert()
  }, { scope: pageRef, dependencies: [product?.id] })
  if (productQuery.isLoading) return <div className="bakery-loading-row">Finishing the details…</div>
  if (productQuery.isError) return <BakeryStatePanel title="THAT CAKE DIDN’T LOAD" description="The design is still here—retry the bakery connection." actionLabel="TRY AGAIN" onAction={() => void productQuery.refetch()} />
  if (!product) return <BakeryStatePanel title="WE COULDN’T FIND THAT BAKE" description="It may have moved off today’s counter." actionLabel="BROWSE CAKES" link="/bakery/app/cakes" />
  const addPreset = (kind: 'classic' | 'eggless' | 'party') => actions.add.mutate({ productId: product.id, selections: presetSelections(product, kind) }, { onSuccess: () => setAddedPreset(kind) })
  const related = (catalog.data?.products ?? []).filter((item) => item.id !== product.id && (item.style === product.style || item.category === product.category)).slice(0, 3)
  return <div ref={pageRef} className="bakery-product-story"><div className="bakery-product-page"><div ref={imageRef} className="bakery-detail-image"><img src={getBakeryProductAsset(product.id)} alt={product.name} /><span className="bakery-sticker tasty">{product.bestseller ? 'MOST LOVED' : 'HANDMADE'}</span>{!product.available && <div className="bakery-image-unavailable"><span>BAKING PAUSED</span><b>Temporarily unavailable</b></div>}</div><div className="bakery-detail-copy"><span className="bakery-kicker">{product.style?.replaceAll('_', ' ') ?? bakeryCategoryLabels[product.category]}</span><h1>{product.name}</h1><p>{product.description}</p><div className="bakery-detail-facts"><span><Clock3 /><b>{product.leadHours ? `Ready in ${product.leadHours} hours` : 'Ready now'}</b></span><span><Gift /><b>{product.servingLabel}</b></span>{product.egglessAvailable && <span><Leaf /><b>Eggless available</b></span>}</div><strong className="bakery-detail-price">FROM ₹{product.basePrice}</strong>
    {!product.available ? <BakeryStatePanel title="THIS DESIGN IS RESTING" description="The baker has paused this cake for now. Browse available cakes without losing your place." actionLabel="SEE AVAILABLE CAKES" link="/bakery/app/cakes" /> : product.customisable ? <><div className="bakery-quick-heading"><span>QUICK ORDER OR MAKE IT YOURS</span><h2>PICK A READY FORMAT</h2><p>Three balanced combinations, ready to add immediately. Personalisation stays available below.</p></div><div className="bakery-preset-grid"><button disabled={actions.add.isPending} onClick={() => addPreset('classic')}><span className="bakery-preset-icon">A</span><b>BAKER’S CLASSIC</b><span>0.5 kg · signature finish</span><strong>{addedPreset === 'classic' ? 'ADDED ✓' : `₹${product.basePrice}`}</strong></button><button disabled={actions.add.isPending} onClick={() => addPreset('eggless')}><span className="bakery-preset-icon">E</span><b>EGGLESS FAVOURITE</b><span>0.5 kg · eggless sponge</span><strong>{addedPreset === 'eggless' ? 'ADDED ✓' : `₹${product.basePrice + 60}`}</strong></button><button disabled={actions.add.isPending} onClick={() => addPreset('party')}><span className="bakery-preset-icon">P</span><b>PARTY SIZE</b><span>1 kg · serves 8–12</span><strong>{addedPreset === 'party' ? 'ADDED ✓' : `₹${product.basePrice + 380}`}</strong></button></div>{actions.add.isError && <p className="bakery-validation">We couldn’t add that format. Please try once more.</p>}<Link className="bakery-button primary wide bakery-sticky-action" to={`/bakery/app/design/${product.id}`}>PERSONALISE THIS CAKE <Sparkles /></Link></> : <button className="bakery-button primary wide" onClick={() => actions.add.mutate({ productId: product.id })}>ADD TO BOX · ₹{product.basePrice}</button>}
    <small className="bakery-detail-note">Final appearance is handcrafted and may vary slightly—that is part of the charm.</small></div></div>
    {product.customisable && <section className="bakery-product-inspiration"><span className="bakery-kicker">START WITH A FEELING</span><h2>ONE CAKE, <span className="bakery-inline-cake"><img src={getBakeryProductAsset(product.id)} alt="" /></span> YOUR MOMENT.</h2><p>Switch the visual direction before opening the studio. Your size, flavour and message remain yours to choose.</p><div className="bakery-style-accordion">{styles.map((style) => <Link key={style.id} to={`/bakery/app/styles/${style.id.toLowerCase()}`} style={{ backgroundImage: `linear-gradient(180deg, transparent 35%, rgba(45, 22, 18, .84)), url(${style.image})` }}><span><Palette />{style.label}</span><p>{style.description}</p></Link>)}</div></section>}
    {related.length > 0 && <section className="bakery-product-related"><BakerySectionTitle eyebrow="KEEP EXPLORING" title="MORE FOR THE MOMENT" /><div className="bakery-product-grid">{related.map((item) => <BakeryProductCard key={item.id} product={item} />)}</div></section>}
    <section className="bakery-product-assurance"><article><Check /><b>PRICE UPDATES LIVE</b><p>No surprise customization cost at checkout.</p></article><article><Clock3 /><b>LEAD TIME SHOWN EARLY</b><p>Choose with the celebration date in mind.</p></article><article><Gift /><b>HAND-FINISHED</b><p>Every design is made by a baker, not a mould.</p></article></section>
  </div>
}
