import { AlertTriangle, ArrowLeft, Check, ChefHat, Clock3, LogOut, PackageCheck, Search, TimerReset } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link, NavLink, Outlet, useParams } from 'react-router-dom'
import type { BakeryProductionStatus } from '../../../domain/bakery/bakery.types'
import { useBakeryAdmin, useBakeryAvailability, useBakeryOperations, useBakeryOrder } from '../../../features/bakery/useBakery'
import { getBakeryProductAsset } from '../../../shared/utils/bakeryAssets'
import { BakeryLogo, BakeryStatePanel } from '../components/BakeryUi'

const sessionKey = 'bakery-wave:session:production'

function ProductionLogin({ onSuccess }: { onSuccess: () => void }) {
  const [pin, setPin] = useState(''); const [error, setError] = useState('')
  const submit = (event: FormEvent) => { event.preventDefault(); if (pin === '2580') { sessionStorage.setItem(sessionKey, 'active'); onSuccess() } else setError('Use the demo baker PIN: 2580') }
  return <main className="bakery-production-login"><form onSubmit={submit}><ChefHat /><span className="bakery-kicker">KITCHEN TABLET #1</span><h1>PRODUCTION SIGN IN</h1><p>Large controls, clear due times and the details that cannot be missed.</p><label><span>4-digit baker PIN</span><input autoFocus inputMode="numeric" maxLength={4} value={pin} onChange={(event) => setPin(event.target.value.replace(/\D/g, ''))} /></label>{error && <p className="bakery-form-error">{error}</p>}<button type="submit" className="bakery-button primary wide">OPEN PRODUCTION</button><small>Demo PIN · 2580</small></form></main>
}

export function BakeryProductionShell() {
  const [loggedIn, setLoggedIn] = useState(() => sessionStorage.getItem(sessionKey) === 'active')
  if (!loggedIn) return <ProductionLogin onSuccess={() => setLoggedIn(true)} />
  return <div className="bakery-production"><header><div className="bakery-production-brand"><BakeryLogo compact /><span>BAKE KDS</span></div><nav aria-label="Production navigation"><NavLink end to="/bakery/production/">QUEUE</NavLink><NavLink to="/bakery/production/availability">AVAILABILITY</NavLink></nav><div className="bakery-production-device"><span><i /> KITCHEN TABLET #1</span><button type="button" aria-label="Sign out of production" onClick={() => { sessionStorage.removeItem(sessionKey); setLoggedIn(false) }}><LogOut /></button></div></header><Outlet /></div>
}

const groups: Array<{ title: string; statuses: BakeryProductionStatus[]; tone: string }> = [
  { title: 'START NOW', statuses: ['SCHEDULED'], tone: 'red' }, { title: 'IN PROGRESS', statuses: ['MIXING', 'BAKING', 'COOLING', 'DECORATING', 'PACKING'], tone: 'yellow' }, { title: 'READY', statuses: ['READY'], tone: 'green' },
]

export function BakeryProductionQueuePage() {
  const admin = useBakeryAdmin(); const operations = useBakeryOperations(); const allOrders = Array.isArray(admin.data?.orders) ? admin.data.orders : []; const orders = allOrders.filter((order) => !['AWAITING_ACCEPTANCE', 'REJECTED', 'COMPLETED'].includes(order.productionStatus))
  if (admin.isLoading) return <main className="bakery-production-main"><div className="bakery-loading-row">Sorting the production queue…</div></main>
  if (admin.isError) return <main className="bakery-production-main"><BakeryStatePanel title="QUEUE DIDN’T LOAD" description="No ticket has been changed. Retry the kitchen connection." actionLabel="TRY AGAIN" onAction={() => void admin.refetch()} /></main>
  return <main className="bakery-production-main"><header className="bakery-production-heading"><div><span>MONDAY · 21 SEPTEMBER</span><h1>PRODUCTION QUEUE</h1></div><div><Clock3 /><span><b>{orders.length} live orders</b><small>System-sorted by promised time</small></span></div></header>{groups.map((group) => <section className="bakery-ticket-lane" key={group.title}><div><span className={group.tone} /><h2>{group.title}</h2><b>{orders.filter((order) => group.statuses.includes(order.productionStatus)).length}</b></div><div className="bakery-ticket-grid">{orders.filter((order) => group.statuses.includes(order.productionStatus)).map((order) => <article key={order.id}><header><b>{order.publicNumber}</b><span>{order.fulfillment}</span></header><p className="bakery-ticket-time"><span>DUE</span><strong>{order.slot}</strong></p><div>{(Array.isArray(order.items) ? order.items : []).map((item) => <p key={item.id}><b>{item.quantity} × {item.product?.name ?? 'Bakery item'}</b><span>{item.message && `WRITE: ${item.message}`}</span></p>)}</div>{order.productionStatus === 'SCHEDULED' ? <button disabled={operations.status.isPending} onClick={() => operations.status.mutate({ orderId: order.id, status: 'MIXING' })}>START PRODUCTION</button> : <Link to={`/bakery/production/order/${order.id}`}>OPEN ORDER <ArrowRight /></Link>}</article>)}</div></section>)}{!orders.length && <div className="bakery-production-empty"><PackageCheck /><h2>NO ACCEPTED ORDERS YET</h2><p>Complete a customer payment and accept it in Founder Control.</p></div>}</main>
}

const nextStatus: Partial<Record<BakeryProductionStatus, BakeryProductionStatus>> = { SCHEDULED: 'MIXING', MIXING: 'BAKING', BAKING: 'COOLING', COOLING: 'DECORATING', DECORATING: 'PACKING', PACKING: 'READY', READY: 'COMPLETED' }
export function BakeryProductionOrderPage() {
  const { orderId } = useParams(); const order = useBakeryOrder(orderId); const operations = useBakeryOperations(); const [problemOpen, setProblemOpen] = useState(false); const [reportedProblem, setReportedProblem] = useState(''); const value = order.data
  if (order.isError) return <main className="bakery-production-main"><BakeryStatePanel title="TICKET NOT FOUND" description="Return to the queue and choose an active production ticket." actionLabel="BACK TO QUEUE" link="/bakery/production/" /></main>
  if (!value) return <main className="bakery-production-main">Loading production ticket…</main>
  const items = Array.isArray(value.items) ? value.items : []
  const selections = items.flatMap((item) => (Array.isArray(item.selections) ? item.selections : []).flatMap((selection) => Array.isArray(selection.optionIds) ? selection.optionIds : []))
  const advance = nextStatus[value.productionStatus]
  return <main className="bakery-production-main"><Link className="bakery-back-link" to="/bakery/production/"><ArrowLeft /> BACK TO QUEUE</Link><section className="bakery-production-order-head"><div><span>{value.publicNumber} · {value.fulfillment}</span><h1>{value.productionStatus.replaceAll('_', ' ')}</h1><p>Target ready: {value.eventDate} · {value.slot}</p></div><div className="bakery-big-timer"><TimerReset /><b>01:42:18</b><span>TO PROMISE</span></div></section>{reportedProblem && <p className="bakery-problem-confirmed"><AlertTriangle /> {reportedProblem} recorded for this demo ticket.</p>}<div className="bakery-production-order-grid"><section><img src={getBakeryProductAsset(items[0]?.productId ?? '')} alt="" /><span>CAKE REFERENCE</span></section><section><span className="bakery-kicker">CRITICAL DETAILS</span><div className="bakery-critical-tags">{selections.filter((selection) => ['eggless', 'one-kg', 'two-kg', 'heart', 'photo', 'fondant'].includes(selection)).map((selection) => <strong key={selection}>{selection.replaceAll('-', ' ').toUpperCase()}</strong>)}{items.some((item) => item.message) && <strong>WRITE “{items.find((item) => item.message)?.message?.toUpperCase()}”</strong>}</div><h2>PRODUCTION NOTES</h2>{items.map((item) => <article key={item.id}><h3>{item.quantity} × {item.product?.name ?? 'Bakery item'}</h3><p>{(Array.isArray(item.selections) ? item.selections : []).flatMap((selection) => Array.isArray(selection.optionIds) ? selection.optionIds : []).join(' · ').replaceAll('-', ' ')}</p></article>)}{value.note && <p className="bakery-kitchen-note"><AlertTriangle /> {value.note}</p>}</section></div><footer className="bakery-production-actions"><button type="button" onClick={() => setProblemOpen(true)}><AlertTriangle /> REPORT PROBLEM</button>{advance && <button className="primary" disabled={operations.status.isPending} onClick={() => operations.status.mutate({ orderId: value.id, status: advance })}>{advance === 'READY' ? 'MARK READY' : advance === 'COMPLETED' ? 'COMPLETE HANDOVER' : `MOVE TO ${advance}`} <Check /></button>}</footer>{problemOpen && <div className="bakery-sheet-backdrop" role="presentation" onMouseDown={() => setProblemOpen(false)}><section className="bakery-production-problem" role="dialog" aria-modal="true" aria-labelledby="bakery-problem-title" onMouseDown={(event) => event.stopPropagation()}><span className="bakery-kicker">PRODUCTION EXCEPTION</span><h2 id="bakery-problem-title">REPORT A PROBLEM</h2><p>Choose the clearest reason. This records a demo ticket note without changing the promised time.</p>{['Ingredient unavailable', 'Kitchen delay', 'Equipment issue', 'Other'].map((reason) => <button type="button" key={reason} onClick={() => { setReportedProblem(reason); setProblemOpen(false) }}>{reason}<ArrowRight /></button>)}<button className="bakery-sheet-close" type="button" onClick={() => setProblemOpen(false)}>CANCEL</button></section></div>}</main>
}

export function BakeryAvailabilityPage() {
  const data = useBakeryAvailability(); const operations = useBakeryOperations(); const [query, setQuery] = useState(''); const allProducts = Array.isArray(data.data?.products) ? data.data.products : []; const products = allProducts.filter((product) => product.name.toLowerCase().includes(query.toLowerCase()))
  if (data.isLoading) return <main className="bakery-production-main"><div className="bakery-loading-row">Checking the bakery counter…</div></main>
  if (data.isError) return <main className="bakery-production-main"><BakeryStatePanel title="AVAILABILITY DIDN’T LOAD" description="Customer items remain unchanged. Retry before pausing a product." actionLabel="TRY AGAIN" onAction={() => void data.refetch()} /></main>
  return <main className="bakery-production-main"><header className="bakery-production-heading"><div><span>COUNTER & INGREDIENT CONTROL</span><h1>AVAILABILITY</h1></div></header><label className="bakery-production-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search cakes or bakes" /></label><div className="bakery-availability-list">{products.map((product) => <article key={product.id}><img src={getBakeryProductAsset(product.id)} alt="" /><div><small>{product.category}</small><h2>{product.name}</h2><p>{product.available ? 'Available to customers' : 'Temporarily unavailable'}</p></div><span className={product.available ? 'on' : 'off'}>{product.available ? 'LIVE' : 'OFF'}</span><button disabled={operations.availability.isPending} onClick={() => operations.availability.mutate({ productId: product.id, available: !product.available, source: 'BAKER', reason: 'Production capacity', until: !product.available ? undefined : new Date(Date.now() + 3600000).toISOString() })}>{product.available ? 'PAUSE 1 HOUR' : 'ENABLE NOW'}</button></article>)}</div>{!products.length && <div className="bakery-production-empty"><Search /><h2>NO MATCHING ITEMS</h2><p>Try another cake or bake name.</p></div>}</main>
}

function ArrowRight() { return <span aria-hidden="true">→</span> }
