import { AlertTriangle, ArrowRight, BarChart3, BellRing, CakeSlice, CalendarDays, Check, Clock3, Gift, LayoutDashboard, LockKeyhole, LogOut, Search, Settings2, Sparkles, UsersRound } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import type { BakeryProductionStatus } from '../../../domain/bakery/bakery.types'
import { useBakeryAdmin, useBakeryOperations } from '../../../features/bakery/useBakery'
import { BakeryLogo, BakeryStatePanel } from '../components/BakeryUi'

const sessionKey = 'bakery-wave:session:owner'
type Section = 'today' | 'calendar' | 'requests' | 'customers' | 'growth' | 'settings'

function readOwner() { return sessionStorage.getItem(sessionKey) === 'active' }

function OwnerLogin({ onSuccess }: { onSuccess: () => void }) {
  const [email, setEmail] = useState('owner@bakerywave.demo'); const [password, setPassword] = useState(''); const [code, setCode] = useState(''); const [error, setError] = useState('')
  const submit = (event: FormEvent) => { event.preventDefault(); if (email === 'owner@bakerywave.demo' && password === 'BakeryWave@123' && code === '654321') { sessionStorage.setItem(sessionKey, 'active'); onSuccess() } else setError('Use the frozen bakery demo credentials shown below.') }
  return <main className="bakery-owner-login"><section><BakeryLogo /><span>GRAND ROAD · CUTTACK</span><h1>RUN THE DAY.<br />PROTECT THE MOMENTS.</h1><p>Production, customer context and custom-cake decisions in one calm control room.</p></section><form onSubmit={submit}><LockKeyhole /><span className="bakery-kicker">FOUNDER CONTROL</span><h2>OWNER SIGN IN</h2><label><span>Email</span><input value={email} onChange={(event) => setEmail(event.target.value)} /></label><label><span>Password</span><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label><label><span>6-digit 2FA</span><input inputMode="numeric" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ''))} /></label>{error && <p className="bakery-form-error">{error}</p>}<button type="submit" className="bakery-button primary wide">ENTER CONTROL ROOM <ArrowRight /></button><small>owner@bakerywave.demo · BakeryWave@123 · 654321</small></form></main>
}

export default function BakeryOwnerPage() {
  const [loggedIn, setLoggedIn] = useState(readOwner); const [section, setSection] = useState<Section>('today'); const [overlay, setOverlay] = useState<{ eyebrow: string; title: string; body: string } | null>(null); const admin = useBakeryAdmin(); const operations = useBakeryOperations()
  if (!loggedIn) return <OwnerLogin onSuccess={() => setLoggedIn(true)} />
  if (admin.isLoading) return <main className="bakery-owner-login"><div className="bakery-loading-row">Opening Founder Control…</div></main>
  if (admin.isError) return <main className="bakery-owner-login"><BakeryStatePanel title="CONTROL ROOM DIDN’T LOAD" description="No bakery data was changed. Retry the local demo connection." actionLabel="TRY AGAIN" onAction={() => void admin.refetch()} /></main>
  const orders = Array.isArray(admin.data?.orders) ? admin.data.orders : []; const requests = Array.isArray(admin.data?.requests) ? admin.data.requests : []; const attention = orders.filter((order) => order.productionStatus === 'AWAITING_ACCEPTANCE').length + requests.filter((request) => request.status === 'NEW').length
  const move = (orderId: string, status: BakeryProductionStatus) => operations.status.mutate({ orderId, status })
  return <div className="bakery-owner"><aside><div className="bakery-owner-brand"><BakeryLogo /><span>FOUNDER CONTROL</span></div><nav aria-label="Founder control navigation">{[
    ['today', <LayoutDashboard />, 'Today'], ['calendar', <CalendarDays />, 'Cake calendar'], ['requests', <Sparkles />, 'Custom requests'], ['customers', <UsersRound />, 'Customers'], ['growth', <BarChart3 />, 'Growth'], ['settings', <Settings2 />, 'Configuration'],
  ].map(([id, icon, label]) => <button type="button" className={section === id ? 'active' : ''} onClick={() => setSection(id as Section)} key={id as string}>{icon}<span>{label}</span></button>)}</nav><div><Link to="/bakery/production/">OPEN PRODUCTION →</Link><button type="button" onClick={() => { sessionStorage.removeItem(sessionKey); setLoggedIn(false) }}><LogOut /> Sign out</button></div></aside><main><header className="bakery-owner-top"><div><span>MONDAY · GRAND ROAD</span><h1>Good afternoon, founder.</h1></div><div><span className="bakery-attention"><BellRing /> {attention} need you</span><Link className="bakery-button primary" to="/bakery/app/">VIEW CUSTOMER APP</Link></div></header>
    {section === 'today' && <><section className="bakery-owner-hero"><div><span className="bakery-kicker">NEEDS YOUR ATTENTION</span><h2>{attention ? `${attention} DECISIONS, NOT 40 ROUTINE ORDERS.` : 'THE BAKERY IS RUNNING CLEAN.'}</h2><p>Only custom requests, capacity conflicts and paid exceptions surface here.</p></div><AlertTriangle /></section><section className="bakery-owner-kpis"><article><span>REVENUE</span><h2>₹{admin.data?.revenue?.toLocaleString('en-IN') ?? 0}</h2><p>Confirmed bakery payments</p></article><article><span>PAID ORDERS</span><h2>{orders.length}</h2><p>Across delivery and pickup</p></article><article><span>CUSTOM REQUESTS</span><h2>{requests.length}</h2><p>Founder-reviewed work</p></article><article><span>PRODUCTION HEALTH</span><h2>92%</h2><p>Slots running on promise</p></article></section><div className="bakery-owner-columns"><section><div className="bakery-owner-section-title"><div><span>LIVE OPERATIONS</span><h2>PAID & IN PRODUCTION</h2></div><Search /></div>{orders.length ? <div className="bakery-owner-orders">{orders.map((order) => <article key={order.id}><span className="bakery-order-icon"><CakeSlice /></span><div><small>{order.publicNumber} · {order.fulfillment}</small><h3>{order.items?.[0]?.product?.name ?? 'Custom cake'}</h3><p><Clock3 /> Due {order.eventDate} · {order.slot}</p></div><strong>{order.productionStatus.replaceAll('_', ' ')}</strong>{order.productionStatus === 'AWAITING_ACCEPTANCE' && <div><button disabled={operations.status.isPending} onClick={() => move(order.id, 'SCHEDULED')}><Check /> ACCEPT</button><button disabled={operations.status.isPending} onClick={() => move(order.id, 'REJECTED')}>REJECT</button></div>}</article>)}</div> : <div className="bakery-owner-empty">No paid bakery orders yet. Complete a customer payment to populate this queue.</div>}</section><section className="bakery-production-health"><span>PRODUCTION LOAD</span><div className="bakery-load-ring"><b>64%</b><small>HEALTHY</small></div><p><span>Baking</span><b>{orders.filter((order) => order.productionStatus === 'BAKING').length}</b></p><p><span>Decorating</span><b>{orders.filter((order) => order.productionStatus === 'DECORATING').length}</b></p><p><span>Ready</span><b>{orders.filter((order) => order.productionStatus === 'READY').length}</b></p><Link to="/bakery/production/">OPEN PRODUCTION BOARD →</Link></section></div></>}
    {section === 'calendar' && <section className="bakery-owner-panel"><span className="bakery-kicker">PROMISE-FIRST PLANNING</span><h2>CAKE CALENDAR</h2><div className="bakery-calendar-strip">{['22 MON', '23 TUE', '24 WED', '25 THU', '26 FRI', '27 SAT', '28 SUN'].map((day, index) => <div className={index === 4 ? 'active' : ''} key={day}><b>{day.split(' ')[0]}</b><span>{day.split(' ')[1]}</span><i>{index === 4 ? 6 : index + 1} cakes</i></div>)}</div><div className="bakery-owner-note"><CalendarDays /><span><b>Friday needs attention</b><p>Two custom cakes share the 6:00 PM promise window. The scheduling engine will require review if another complex order arrives.</p></span></div></section>}
    {section === 'requests' && <section className="bakery-owner-panel"><span className="bakery-kicker">BESPOKE WORK</span><h2>CUSTOM REQUESTS</h2>{requests.length ? requests.map((request) => <article className="bakery-request-row" key={request.id}><Gift /><div><small>{request.event.replaceAll('_', ' ')} · {request.eventDate}</small><h3>{request.servings} guests · {request.budget}</h3><p>{request.notes}</p></div><button type="button" onClick={() => setOverlay({ eyebrow: 'BESPOKE REQUEST', title: `${request.event.replaceAll('_', ' ')} · ${request.eventDate}`, body: `${request.servings} guests · ${request.budget}. ${request.notes || 'No extra customer note.'} This prototype keeps quoting as a founder-reviewed decision.` })}>REVIEW REQUEST</button></article>) : <p>No bespoke requests yet. Submit one from the customer app to see it here.</p>}</section>}
    {section === 'customers' && <section className="bakery-owner-panel"><span className="bakery-kicker">CUSTOMER 360</span><h2>PRIYANSHU</h2><div className="bakery-customer-360"><article><b>GOLD MEMBER</b><h3>182 Sweet Points</h3><p>Favourite: chocolate and vintage-piped cakes</p></article><article><b>NEXT CELEBRATION</b><h3>26 September</h3><p>Birthday reminder scheduled</p></article><article><b>LIFETIME VALUE</b><h3>₹4,880</h3><p>4 completed bakery orders</p></article></div></section>}
    {section === 'growth' && <section className="bakery-owner-panel"><span className="bakery-kicker">USEFUL, NOT NOISY</span><h2>RETENTION OPPORTUNITIES</h2><div className="bakery-growth-list"><article><b>BIRTHDAYS IN 7 DAYS</b><strong>24 customers</strong><button type="button" onClick={() => setOverlay({ eyebrow: 'CAMPAIGN PREVIEW', title: 'YOUR CELEBRATION IS ALMOST HERE 🎂', body: 'Audience: 24 customers · Channel: in-app + WhatsApp simulation · Timing: seven days before the saved birthday.' })}>PREVIEW CAMPAIGN</button></article><article><b>SECOND CAKE PENDING</b><strong>18 customers</strong><button type="button" onClick={() => setOverlay({ eyebrow: 'CAMPAIGN PREVIEW', title: 'ONE MORE CAKE UNLOCKS YOUR NEXT MILESTONE', body: 'Audience: 18 first-order customers · Offer: bonus Sweet Points · Timing: after the first completed celebration.' })}>PREVIEW CAMPAIGN</button></article><article><b>SAVED DESIGN, NO ORDER</b><strong>11 customers</strong><button type="button" onClick={() => setOverlay({ eyebrow: 'CAMPAIGN PREVIEW', title: 'YOUR SAVED DESIGN IS READY WHEN YOU ARE', body: 'Audience: 11 customers · Channel: in-app reminder · Timing: 48 hours after saving a cake without ordering.' })}>PREVIEW CAMPAIGN</button></article></div></section>}
    {section === 'settings' && <section className="bakery-owner-panel"><span className="bakery-kicker">BUSINESS CONTROLS</span><h2>CONFIGURATION</h2><div className="bakery-setting-list"><p><span>Store ordering</span><b>ON</b></p><p><span>Delivery</span><b>ON</b></p><p><span>Pickup</span><b>ON</b></p><p><span>Safe-order auto acceptance</span><b>HYBRID</b></p><p><span>Production capacity</span><b>8 concurrent cakes</b></p></div></section>}
    {overlay && <div className="bakery-sheet-backdrop" role="presentation" onMouseDown={() => setOverlay(null)}><section className="bakery-owner-dialog" role="dialog" aria-modal="true" aria-labelledby="bakery-owner-dialog-title" onMouseDown={(event) => event.stopPropagation()}><span className="bakery-kicker">{overlay.eyebrow}</span><h2 id="bakery-owner-dialog-title">{overlay.title}</h2><p>{overlay.body}</p><button className="bakery-button primary" type="button" onClick={() => setOverlay(null)}>DONE</button></section></div>}
  </main></div>
}
